version: "3.8"

services:
  starknet:
    image: shardlabs/starknet-devnet
    command: "--seed 0"
    container_name: "starknet"
    ports:
     - "5050:5050"
    networks:
      default:
        aliases:
          - starknet.local

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true

    volumes:
      - type: bind
        source: ./backend
        target: /workspaces

      - type: volume
        source: backend-node-modules
        target: /workspaces/node_modules

networks:
  default:
    driver: bridge
    
volumes:
  backend-node-modules: